/**
 * PPTX 렌더러 — AI JSON → PowerPoint 파일 변환
 * pptxgenjs 사용
 */

import type { PptxSlide, RenderOutput, CorporateTheme } from './types';
import { DEFAULT_THEME } from './types';

export async function renderPptx(
  slides: PptxSlide[],
  title: string,
  theme: CorporateTheme = DEFAULT_THEME,
): Promise<RenderOutput> {
  const pptxgen = (await import('pptxgenjs')).default;
  const pres = new pptxgen();

  pres.author = 'CLIO AI';
  pres.title = title;
  pres.layout = 'LAYOUT_16x9';

  // 기업 테마 색상
  const primary = `#${theme.primaryColor}`;
  const bgColor = '#F7F8FA';
  const textDark = '#1B1F2B';

  // 표지 슬라이드
  const coverSlide = pres.addSlide();
  coverSlide.background = { color: theme.primaryColor };
  coverSlide.addText(title, {
    x: 0.8, y: 1.5, w: 8.4, h: 2,
    fontSize: 36,
    fontFace: theme.fontFamily,
    color: 'FFFFFF',
    bold: true,
    align: 'left',
    valign: 'middle',
  });
  coverSlide.addText('Generated by CLIO AI', {
    x: 0.8, y: 4, w: 8.4, h: 0.5,
    fontSize: 14,
    fontFace: 'Arial',
    color: 'CCCCCC',
    align: 'left',
  });

  // 콘텐츠 슬라이드
  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: bgColor.replace('#', '') };

    // 상단 액센트 바
    s.addShape(pres.ShapeType.rect, {
      x: 0, y: 0, w: 10, h: 0.06,
      fill: { color: theme.primaryColor },
    });

    // 제목
    s.addText(slide.title, {
      x: 0.8, y: 0.3, w: 8.4, h: 0.8,
      fontSize: 24,
      fontFace: theme.fontFamily,
      color: textDark.replace('#', ''),
      bold: true,
      align: 'left',
      valign: 'middle',
    });

    let yPos = 1.3;

    // 본문
    if (slide.body) {
      s.addText(slide.body, {
        x: 0.8, y: yPos, w: 8.4, h: 1.2,
        fontSize: 16,
        fontFace: theme.fontFamily,
        color: '555555',
        align: 'left',
        valign: 'top',
        wrap: true,
      });
      yPos += 1.4;
    }

    // 불릿 포인트
    if (slide.bullets && slide.bullets.length > 0) {
      const bulletTexts = slide.bullets.map(b => ({
        text: b,
        options: {
          fontSize: 15,
          fontFace: theme.fontFamily,
          color: textDark.replace('#', ''),
          bullet: { type: 'bullet' as const },
          paraSpaceBefore: 6,
          paraSpaceAfter: 6,
        },
      }));

      s.addText(bulletTexts, {
        x: 0.8, y: yPos, w: 8.4, h: 5.6 - yPos,
        valign: 'top',
      });
    }

    // 페이지 번호
    s.addText(`${slides.indexOf(slide) + 1} / ${slides.length}`, {
      x: 8.5, y: 5.2, w: 1.2, h: 0.4,
      fontSize: 10,
      fontFace: 'Arial',
      color: '999999',
      align: 'right',
    });
  }

  // pptxgenjs는 write('nodebuffer')로 Buffer 반환
  const data = await pres.write({ outputType: 'nodebuffer' }) as Buffer;
  const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data as ArrayBuffer);

  return {
    buffer,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    extension: 'pptx',
    fileName: `${title}.pptx`,
  };
}
