import type { TemplateBundle, TemplateFieldDefinition, TemplateSectionDefinition } from '@/lib/templates/template-schema';

const BUSINESS_PLAN_PATTERN = /^사업계획서$/;

export const BUSINESS_PLAN_FIELDS: TemplateFieldDefinition[] = [
  { key: 'company_name', label: '기업체명', type: 'text', required: true, placeholder: '예: 클리오 주식회사' },
  { key: 'ceo_name', label: '대표자', type: 'text', required: true, placeholder: '예: 홍길동' },
  { key: 'ceo_birth', label: '생년월일', type: 'text', placeholder: '예: 1990.01.01' },
  { key: 'corp_reg_number', label: '법인등록번호', type: 'text', placeholder: '예: 110111-1234567' },
  { key: 'biz_reg_number', label: '사업자등록번호', type: 'text', placeholder: '예: 123-45-67890' },
  { key: 'established_date', label: '설립(예정)일', type: 'text', placeholder: '예: 2024.01.15' },
  { key: 'biz_type', label: '사업유형', type: 'text', placeholder: '예: 법인사업자 / 개인사업자 / 예비창업자' },
  { key: 'address', label: '대표주소(본점 소재지)', type: 'text', placeholder: '예: 서울특별시 광진구 능동로 120' },
  { key: 'phone', label: '대표자 휴대폰', type: 'text', placeholder: '예: 010-1234-5678' },
  { key: 'email', label: '대표자 이메일', type: 'text', placeholder: '예: ceo@company.com' },
  { key: 'main_biz_name', label: '주요 사업명', type: 'text', required: true, placeholder: '예: AI 기반 문서 자동화 플랫폼' },
  { key: 'biz_summary', label: '사업개요', type: 'textarea', required: true, placeholder: '예: AI 기술을 활용한 기업 문서 작성 자동화 SaaS 서비스' },
];

export const BUSINESS_PLAN_SECTIONS: TemplateSectionDefinition[] = [
  {
    key: 'product_overview',
    title: '창업제품(서비스) 개요',
    prompt: [
      '### 핵심 기술 및 사업 분야',
      '자사가 속한 핵심 기술 및 사업 분야를 명시하고 해당 분야에서의 포지셔닝을 설명합니다.',
      '### 창업제품(서비스) 개발동기',
      '자사가 개발(보유)하고 있는 제품·서비스에 대한 개발동기를 기재합니다.',
      '제품(서비스)을 구현하고자 하는 목적을 구체적으로 서술합니다.',
      '### 창업제품(서비스) 소개',
      '제품(서비스)의 핵심기능(스펙, 서비스 등), 사용 방법을 기재합니다.',
      '고객에게 제공할 기능과 서비스를 구체적으로 나열합니다.',
      '### 창업제품(서비스)의 차별성',
      '경쟁사 및 경쟁사 제품(서비스)과의 차별성을 기재합니다.',
      '경쟁제품과 당사제품의 차이점, 고객 만족도 향상 방법 및 차별요소를 설명합니다.',
      '### 국내외 목표시장',
      '국내·외 목표시장, 판매 전략 등을 기재합니다.',
    ].join('\n'),
  },
  {
    key: 'technology',
    title: '1. 기술성',
    prompt: [
      '### 1-1. 제품(서비스)의 개요',
      '개발대상 및 보유기술(또는 제품)의 기본개념을 제시하고 문제점과 전망을 서술합니다.',
      '### 1-2. 아이템의 기술적 우수성(차별성)과 기술보유 형태',
      '개발기술(또는 제품)의 독창성, 신규성 및 차별성을 기존기술과 비교하여 설명합니다.',
      '기술 비교 표를 포함합니다: | 구분 | 자사 기술 | 기존 기술 | 차별점 |',
      '### 1-3. 기술개발 로드맵 현황',
      '개발한 기술이 최종 제품·서비스 형태로 개발되는 동안의 계획과정을 기술합니다.',
      '연도별 기술개발 로드맵 표를 포함합니다.',
    ].join('\n'),
  },
  {
    key: 'market',
    title: '2. 시장성',
    prompt: [
      '### 2-1. 아이템의 수요형태와 필요성, 성과 현황',
      '개발대상 및 보유기술(또는 제품)의 수요형태, 고객의 니즈를 혁신적으로 해결하기 위한 방안을 기술합니다.',
      '### 2-2. 국내·외 시장규모 및 경쟁 분석',
      '객관성 있는 산출근거를 바탕으로 시장규모를 제시합니다.',
      '시장규모 표: | 연도 | 국내 시장 | 해외 시장 | 성장률 |',
      '경쟁관계에 있는 국내·외 기관·기업의 제품을 분석합니다.',
      '### 2-3. 수익창출 비즈니스모델과 시장 확장성',
      '수익을 창출하기 위한 비즈니스 모델을 제시합니다.',
      '현재 시장규모에서 어떻게 확장할 것인지 비전을 제시합니다.',
    ].join('\n'),
  },
  {
    key: 'business',
    title: '3. 사업성',
    prompt: [
      '### 3-1. 시장진입 및 고객과 매출 발생',
      '과거 사업화 실적 및 예상 매출을 기술합니다.',
      '연도별 매출 표: | 구분 | 2023년 | 2024년 | 2025년 | 2026년(예상) |',
      '주요 제품/서비스별, 주요 고객/이용자별 실적을 구분합니다.',
      '### 3-2. 양산 및 마케팅 전략',
      '제품화 이후의 양산 계획과 방법을 기술합니다.',
      '양산제품의 마케팅, 판매전략 등 판로개척 계획을 설명합니다.',
      '### 3-3. 해외 진출 여부',
      '개발대상 기술의 현지 시장분석 및 해외마케팅 전략을 기술합니다.',
      '해외진출 현황 표: | 수출국가수 | 수출액 | 수출품목수 | 수출품목명 |',
      '### 3-4. 자금소요 및 조달계획',
      '소요 예상금액을 운전자금 및 시설자금으로 구분하여 기재합니다.',
      '자금 조달 표: | 구분 | 내용 | 금액 | 조달방법 | 조기조달액 |',
      '투자유치 실적, 향후 투자라운딩 여부 및 기업 Value를 기재합니다.',
    ].join('\n'),
  },
  {
    key: 'organization',
    title: '4. 기업구성',
    prompt: [
      '### 4-1. 대표자 인적사항 및 역량',
      '대표자의 학력, 경력, 특기사항 및 역량을 기재합니다.',
      '### 4-2. 인력 구성',
      '대표자 제외 현재 고용인원 및 향후 고용계획을 기재합니다.',
      '인력 구성 표: | 순번 | 직급 | 성명 | 담당업무 | 주요경력 | 구분 |',
      '### 4-3. 기술개발 및 사업화 실적',
      '과거 기술개발 및 사업화 실적을 정리합니다.',
      '실적 표: | 개발과제명 | 실시기간 | 근무처 | 신청자역할 | 지원기관 | 사업화 현황 |',
      '### 4-4. 정부지원사업 수혜현황',
      '정책자금 및 신용보증 지원현황을 정부사업, R&D사업, 신용보증으로 구분하여 표로 정리합니다.',
    ].join('\n'),
  },
];

export const BUSINESS_PLAN_OUTLINE = [
  '# 사업계획서',
  '## 창업제품(서비스) 개요',
  '## 1. 기술성',
  '## 2. 시장성',
  '## 3. 사업성',
  '## 4. 기업구성',
].join('\n');

function renderSectionPage(section: TemplateSectionDefinition) {
  return [
    '<section class="sheet bp-page">',
    '  <div class="bp-page-header">',
    `    <h2>{{${section.key}_title}}</h2>`,
    '  </div>',
    `  <div class="section-body bp-body">{{${section.key}_body}}</div>`,
    '</section>',
  ].join('\n');
}

function buildBusinessPlanHtml(sections: TemplateSectionDefinition[]) {
  const sectionPages = sections.map((s) => renderSectionPage(s)).join('\n');

  return [
    '<style>',
    '  :root {',
    '    --bp-ink: #000;',
    '    --bp-bg: #fff;',
    '    --bp-label-bg: #f5f5f5;',
    '    --bp-header-bg: #e8e8e8;',
    '    --bp-gap: 8px;',
    '  }',
    '  * { box-sizing: border-box; }',
    '  body { margin: 0; font-family: "Malgun Gothic", "맑은 고딕", "Noto Sans KR", sans-serif; color: var(--bp-ink); background: var(--bp-bg); line-height: 1.5; font-size: 10pt; }',
    '  .bp-document { width: min(210mm, calc(100% - 24px)); margin: 24px auto 56px; }',
    '  .sheet { width: 210mm; min-height: 297mm; background: var(--bp-bg); border: 1px solid #ccc; margin-bottom: 20px; overflow: hidden; position: relative; }',
    '  .bp-cover { padding: 15mm 20mm; }',
    '  .bp-page { padding: 15mm 20mm; display: flex; flex-direction: column; }',
    '  .bp-table { width: 100%; border-collapse: collapse; margin-bottom: 6px; }',
    '  .bp-table th, .bp-table td { border: 1px solid var(--bp-ink); padding: 5px 8px; vertical-align: middle; font-size: 10pt; }',
    '  .bp-table th { background: var(--bp-label-bg); font-weight: bold; text-align: center; }',
    '  .bp-table .bp-label { background: var(--bp-label-bg); text-align: center; font-weight: normal; width: 120px; }',
    '  .bp-title-row td { text-align: center; font-size: 16pt; font-weight: bold; padding: 15px 0; background: var(--bp-bg); }',
    '  .bp-page-header { margin-bottom: 14px; padding: 6px 10px; background: var(--bp-header-bg); border: 1px solid var(--bp-ink); display: inline-block; }',
    '  .bp-page-header h2 { margin: 0; font-size: 12pt; font-weight: bold; }',
    '  .bp-body { flex: 1; font-size: 10.5pt; line-height: 1.7; }',
    '  .bp-body h3 { margin: 16px 0 8px; font-size: 11pt; font-weight: bold; }',
    '  .bp-body h3:first-child { margin-top: 0; }',
    '  .bp-body h4 { margin: 12px 0 6px; font-size: 10.5pt; font-weight: bold; }',
    '  .bp-body p { margin: 4px 0; }',
    '  .bp-body ul, .bp-body ol { margin: 4px 0; padding-left: 20px; }',
    '  .bp-body li { line-height: 1.7; }',
    '  .bp-body table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 9.5pt; }',
    '  .bp-body th, .bp-body td { border: 1px solid var(--bp-ink); padding: 4px 6px; }',
    '  .bp-body th { background: var(--bp-label-bg); text-align: center; font-weight: bold; }',
    '  .bp-attach { border: 1px solid var(--bp-ink); padding: 10px 15px; margin-top: 10px; font-size: 10pt; line-height: 2; }',
    '  @media (max-width: 900px) {',
    '    .bp-document { width: min(100%, calc(100% - 16px)); }',
    '    .sheet { width: 100%; min-height: auto; }',
    '    .bp-cover, .bp-page { padding: 24px 16px; }',
    '  }',
    '</style>',
    '<main class="bp-document">',
    '  <section class="sheet bp-cover">',
    '    <table class="bp-table">',
    '      <colgroup>',
    '        <col style="width:18%"><col style="width:14%"><col style="width:18%">',
    '        <col style="width:14%"><col style="width:18%"><col style="width:18%">',
    '      </colgroup>',
    '      <tbody>',
    '        <tr class="bp-title-row"><td colspan="6"><strong>사 업 계 획 서</strong></td></tr>',
    '        <tr>',
    '          <td class="bp-label">기업체명</td>',
    '          <td colspan="2">{{company_name}}</td>',
    '          <td class="bp-label">대표자</td>',
    '          <td colspan="2">{{ceo_name}}</td>',
    '        </tr>',
    '        <tr>',
    '          <td class="bp-label">법인등록번호</td>',
    '          <td colspan="2">{{corp_reg_number}}</td>',
    '          <td class="bp-label">설립(예정)일</td>',
    '          <td colspan="2">{{established_date}}</td>',
    '        </tr>',
    '        <tr>',
    '          <td class="bp-label">사업자등록번호</td>',
    '          <td colspan="2">{{biz_reg_number}}</td>',
    '          <td class="bp-label">사업유형</td>',
    '          <td colspan="2">{{biz_type}}</td>',
    '        </tr>',
    '        <tr>',
    '          <td class="bp-label">대표주소<br>(본점 소재지)</td>',
    '          <td colspan="2">{{address}}</td>',
    '          <td class="bp-label">대표자연락처</td>',
    '          <td>{{phone}}</td>',
    '          <td>{{email}}</td>',
    '        </tr>',
    '        <tr>',
    '          <td class="bp-label">주요 사업명</td>',
    '          <td colspan="5">{{main_biz_name}}</td>',
    '        </tr>',
    '        <tr>',
    '          <td class="bp-label">사업개요</td>',
    '          <td colspan="5">{{biz_summary}}</td>',
    '        </tr>',
    '      </tbody>',
    '    </table>',
    '    <div class="bp-attach">',
    '      <p>첨부 1. 사업계획서 1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. 벤처기업 확인서 사본 1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. 법인등기부등본(법인) 또는 대표자 주민등록등본(개인) 1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. 지방세 및 국세완납증명 각1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5. 사업자등록증 사본 1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6. 실적 관련 증빙자료 각 1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7. 유망중소기업지정확인서 등 관련 입증자료 각1부</p>',
    '      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8. 개인정보제공이용동의서 1부</p>',
    '    </div>',
    '  </section>',
    `  ${sectionPages}`,
    '</main>',
  ].join('\n');
}

export const BUSINESS_PLAN_TEMPLATE_HTML = buildBusinessPlanHtml(BUSINESS_PLAN_SECTIONS);

export function isBusinessPlanTemplateName(templateName: string | null | undefined) {
  return Boolean(templateName && BUSINESS_PLAN_PATTERN.test(templateName.trim()));
}

export function createBusinessPlanTemplateBundle(): TemplateBundle {
  return {
    version: 1,
    mode: 'html-template',
    layoutHtml: BUSINESS_PLAN_TEMPLATE_HTML,
    outline: BUSINESS_PLAN_OUTLINE,
    fields: [...BUSINESS_PLAN_FIELDS],
    sections: [...BUSINESS_PLAN_SECTIONS],
  };
}
