import type { TemplateBundle, TemplateFieldDefinition } from '@/lib/templates/template-schema';

export const EMPLOYMENT_CERTIFICATE_TEMPLATE_NAME = '재직증명서';

export const EMPLOYMENT_CERTIFICATE_FIELDS: TemplateFieldDefinition[] = [
  { key: 'report_title', label: '문서 제목', type: 'text', required: true, defaultValue: '재직증명서' },
  { key: 'employee_name', label: '성명(한글)', type: 'text', required: true, placeholder: '예: 홍길동' },
  { key: 'resident_registration_no', label: '주민등록번호', type: 'text', placeholder: '예: 900101-1******' },
  { key: 'employee_address', label: '주소', type: 'textarea', placeholder: '예: 서울특별시 강남구 ...' },
  { key: 'department', label: '근무부서', type: 'text', placeholder: '예: 개발팀' },
  { key: 'position', label: '직위', type: 'text', placeholder: '예: 매니저' },
  { key: 'employment_start_date', label: '재직 시작일', type: 'date', required: true },
  { key: 'employment_end_date', label: '재직 기준일', type: 'date', defaultValue: '{{report_date}}', placeholder: '미입력 시 발급일 기준' },
  { key: 'purpose', label: '제출용도', type: 'textarea', placeholder: '예: 금융기관 제출용' },
  { key: 'report_date', label: '발급일', type: 'date', autoFill: 'document' },
  { key: 'company_name', label: '회사명', type: 'text', defaultValue: '주식회사 비엠아이씨앤에스' },
  { key: 'representative_name', label: '대표자', type: 'text', defaultValue: '김동의' },
  { key: 'business_registration_no', label: '사업자등록번호', type: 'text', defaultValue: '263-87-03481' },
  { key: 'company_address', label: '회사 주소', type: 'textarea', defaultValue: '서울특별시 강남구 강남대로 354(혜천빌딩) 1126-5호' },
  { key: 'company_phone', label: '회사 전화', type: 'text', defaultValue: '010-8490-9271' },
];

export const EMPLOYMENT_CERTIFICATE_OUTLINE = [
  '# 재직증명서',
  '## 인적사항',
  '## 재직사항 및 제출용도',
  '## 증명 및 회사 정보',
].join('\n');

export const EMPLOYMENT_CERTIFICATE_TEMPLATE_HTML = [
  '<style>',
  '@page{size:A4;margin:0;}',
  '.employment-cert{box-sizing:border-box;width:210mm;min-height:297mm;margin:0 auto;padding:31mm 29mm 22mm;background:#fff;color:#111;font-family:"Nanum Myeongjo","Batang","AppleMyungjo","Malgun Gothic",serif;font-size:18px;line-height:1.45;word-break:keep-all;}',
  '.employment-cert *{box-sizing:border-box;}',
  '.employment-cert h1{margin:0 0 26mm;text-align:center;font-size:42px;line-height:1.2;font-weight:700;letter-spacing:18px;}',
  '.employment-cert .section-title{margin:0 0 12px 8px;font-size:20px;font-weight:700;}',
  '.employment-cert .section-title--second{margin-top:17mm;}',
  '.employment-cert table{width:100%;border-collapse:collapse;table-layout:fixed;}',
  '.employment-cert td{height:46px;border:1px solid #111;padding:8px 10px;vertical-align:middle;font-size:18px;line-height:1.35;}',
  '.employment-cert .label{width:126px;text-align:center;white-space:nowrap;}',
  '.employment-cert .label-wide{width:128px;text-align:center;white-space:nowrap;}',
  '.employment-cert .value{font-family:"Malgun Gothic","Apple SD Gothic Neo",sans-serif;font-size:15px;}',
  '.employment-cert .address-row td{height:54px;}',
  '.employment-cert .purpose-row td{height:52px;}',
  '.employment-cert .cert-statement{margin:31mm 0 22mm;text-align:center;font-size:20px;}',
  '.employment-cert .issue-date{margin:0 0 35mm;text-align:center;font-size:20px;letter-spacing:14px;}',
  '.employment-cert .company-info{width:360px;margin-left:16px;}',
  '.employment-cert .company-line{display:grid;grid-template-columns:104px 1fr;align-items:start;min-height:39px;font-size:19px;}',
  '.employment-cert .company-label{letter-spacing:8px;white-space:nowrap;}',
  '.employment-cert .company-value{font-family:"Malgun Gothic","Apple SD Gothic Neo",sans-serif;font-size:15px;line-height:1.55;letter-spacing:0;}',
  '.employment-cert .representative-row{display:grid;grid-template-columns:104px 1fr 42px;align-items:center;width:386px;min-height:39px;font-size:19px;}',
  '.employment-cert .seal{text-align:center;}',
  '@media print{html,body{width:210mm;height:297mm;margin:0!important;padding:0!important;background:#fff}.employment-cert{width:210mm;height:297mm;min-height:297mm;margin:0;padding:31mm 29mm 22mm;box-shadow:none;overflow:hidden}}',
  '</style>',
  '<article class="employment-cert">',
  '  <h1>재 직 증 명 서</h1>',
  '  <section>',
  '    <p class="section-title">1. &nbsp;인적사항</p>',
  '    <table>',
  '      <colgroup><col style="width:126px"/><col/><col style="width:128px"/><col/></colgroup>',
  '      <tbody>',
  '        <tr>',
  '          <td class="label">성명&nbsp;&nbsp;(한글)</td>',
  '          <td class="value">{{employee_name}}</td>',
  '          <td class="label-wide">주민등록번호</td>',
  '          <td class="value">{{resident_registration_no}}</td>',
  '        </tr>',
  '        <tr class="address-row">',
  '          <td class="label">주소</td>',
  '          <td class="value" colspan="3">{{employee_address}}</td>',
  '        </tr>',
  '      </tbody>',
  '    </table>',
  '  </section>',
  '  <section>',
  '    <p class="section-title section-title--second">2. &nbsp;재직사항 및 제출용도</p>',
  '    <table>',
  '      <colgroup><col style="width:126px"/><col/><col style="width:128px"/><col/></colgroup>',
  '      <tbody>',
  '        <tr>',
  '          <td class="label">근무부서</td>',
  '          <td class="value">{{department}}</td>',
  '          <td class="label-wide">직위</td>',
  '          <td class="value">{{position}}</td>',
  '        </tr>',
  '        <tr>',
  '          <td class="label">재직기간</td>',
  '          <td class="value" colspan="3">{{employment_start_date_ko}} 부터 {{employment_end_date_ko}} 현재까지</td>',
  '        </tr>',
  '        <tr class="purpose-row">',
  '          <td class="label">제출용도</td>',
  '          <td class="value" colspan="3">{{purpose}}</td>',
  '        </tr>',
  '      </tbody>',
  '    </table>',
  '  </section>',
  '  <p class="cert-statement">위의 기재사항이 사실과 다름없음을 증명합니다.</p>',
  '  <p class="issue-date">{{report_date_ko}}</p>',
  '  <section class="company-info">',
  '    <div class="company-line"><span class="company-label">회 사 명</span><span class="company-value">{{company_name}}</span></div>',
  '    <div class="representative-row"><span class="company-label">대 표 자</span><span class="company-value">{{representative_name}}</span><span class="seal">(인)</span></div>',
  '    <div class="company-line"><span class="company-label">사업자등록</span><span class="company-value">{{business_registration_no}}</span></div>',
  '    <div class="company-line"><span class="company-label">주&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;소</span><span class="company-value">{{company_address}}</span></div>',
  '    <div class="company-line"><span class="company-label">전&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;화</span><span class="company-value">{{company_phone}}</span></div>',
  '  </section>',
  '</article>',
].join('\n');

export function isEmploymentCertificateTemplateName(templateName: string | null | undefined) {
  return Boolean(templateName && /재직\s*증명서/.test(templateName));
}

export function createEmploymentCertificateTemplateBundle(): TemplateBundle {
  return {
    version: 1,
    mode: 'html-template',
    layoutHtml: EMPLOYMENT_CERTIFICATE_TEMPLATE_HTML,
    outline: EMPLOYMENT_CERTIFICATE_OUTLINE,
    fields: EMPLOYMENT_CERTIFICATE_FIELDS,
    sections: [],
  };
}
