import type { TemplateBundle, TemplateFieldDefinition, TemplateSectionDefinition } from '@/lib/templates/template-schema';

const PROPOSAL_TEMPLATE_PATTERN = /^제안서$/;

export const PROPOSAL_FIELDS: TemplateFieldDefinition[] = [
  { key: 'report_title', label: '문서 제목', type: 'text', required: true, placeholder: '예: 2026 통합 운영체계 구축 제안서' },
  { key: 'demand_org', label: '수요기관명', type: 'text', required: true, placeholder: '예: 한국OO공단' },
  { key: 'proposer_name', label: '제안사명', type: 'text', required: true, placeholder: '예: 클리오 주식회사' },
  { key: 'project_name', label: '사업명 또는 과업명', type: 'text', required: true, placeholder: '예: 문서 운영 플랫폼 고도화 사업' },
  { key: 'proposal_objective', label: '제안 목적', type: 'textarea', required: true, placeholder: '예: 기관의 문서 생산성과 협업 흐름을 개선하기 위한 목적과 기대 효과를 입력합니다.' },
  { key: 'scope_summary', label: '핵심 수행 범위', type: 'textarea', required: true, placeholder: '예: 분석, 설계, 구축, 테스트, 교육, 안정화 등 핵심 범위를 입력합니다.' },
  { key: 'special_notes', label: '특기사항 또는 작성 메모', type: 'textarea', required: true, placeholder: '예: 기관 요청사항, 유의점, 강조할 방향, 제외 범위를 입력합니다.' },
];

export const PROPOSAL_SECTIONS: TemplateSectionDefinition[] = [
  {
    key: 'proposal_overview',
    title: '1. 제안 개요',
    prompt: [
      '### 1.1 제안 배경 및 목적',
      '수요기관의 현재 상황과 사업 추진 배경을 3~5문단으로 서술합니다. 제안 목적과 기대 효과를 구체적으로 기술합니다.',
      '### 1.2 사업 개요',
      '사업명, 수요기관, 제안사, 사업 기간, 사업 규모를 항목별로 정리합니다.',
      '### 1.3 제안 범위 요약',
      '본 제안서에서 다루는 핵심 범위를 5~7개 항목으로 요약합니다.',
    ].join('\n'),
  },
  {
    key: 'project_understanding',
    title: '2. 사업 이해 및 추진 방향',
    prompt: [
      '### 2.1 현황 분석 (AS-IS)',
      '수요기관의 현재 업무 환경, 시스템 현황, 운영 프로세스를 분석합니다. 구체적 문제점과 개선 필요성을 3~5개 항목으로 도출합니다.',
      '### 2.2 과업 이해',
      '수요기관이 요구하는 핵심 과업을 정리하고, 과업 간 우선순위와 상호 연관관계를 설명합니다.',
      '### 2.3 추진 방향 (TO-BE)',
      '개선 목표와 추진 전략을 제시합니다. AS-IS 대비 TO-BE 변화 포인트를 구체적으로 대비하여 기술합니다.',
      '### 2.4 핵심 성공 요인',
      '사업 성공을 위한 핵심 성공 요인(CSF) 3~5개를 도출하고 각각의 실행 방안을 기술합니다.',
    ].join('\n'),
  },
  {
    key: 'scope_and_deliverables',
    title: '3. 수행 범위 및 세부 내용',
    prompt: [
      '### 3.1 전체 수행 범위',
      '사업의 전체 수행 범위를 대분류-중분류로 체계적으로 정리합니다.',
      '### 3.2 세부 수행 내용',
      '각 수행 범위별 세부 작업 내용을 구체적으로 기술합니다. 작업별 목적, 방법, 예상 결과물을 포함합니다.',
      '### 3.3 주요 산출물',
      '단계별 산출물 목록을 표로 정리합니다. 산출물명, 설명, 제출 시기, 형식을 포함합니다.',
      '### 3.4 제외 범위',
      '본 사업 범위에서 제외되는 항목이 있으면 명확히 기술합니다.',
    ].join('\n'),
  },
  {
    key: 'execution_plan',
    title: '4. 수행 방법 및 일정 계획',
    prompt: [
      '### 4.1 수행 방법론',
      '본 사업에 적용할 수행 방법론을 제시합니다. 단계별 활동, 기법, 도구를 구체적으로 설명합니다.',
      '### 4.2 단계별 추진 계획',
      '착수 → 분석 → 설계 → 구축 → 시험 → 안정화 등 단계별 주요 활동과 산출물을 기술합니다.',
      '### 4.3 세부 일정 계획',
      '월별 또는 주별 세부 일정을 표로 정리합니다. 각 단계의 시작일, 종료일, 주요 마일스톤을 포함합니다.',
      '### 4.4 주요 마일스톤',
      '사업 전체의 핵심 마일스톤(착수보고, 중간보고, 최종보고 등)을 정리합니다.',
    ].join('\n'),
  },
  {
    key: 'organization_plan',
    title: '5. 수행 조직 및 인력 투입 계획',
    prompt: [
      '### 5.1 수행 조직 구성',
      '프로젝트 수행 조직도를 설명합니다. PM, PL, 개발팀, 품질팀 등 역할별 조직 구성을 기술합니다.',
      '### 5.2 핵심 인력 프로필',
      '주요 투입 인력의 역할, 담당 업무, 자격 요건을 정리합니다.',
      '### 5.3 인력 투입 계획',
      '단계별 투입 인력 수와 투입률을 표로 정리합니다. M/M(Man-Month) 기준으로 산정합니다.',
      '### 5.4 협업 및 의사소통 체계',
      '수요기관과의 협업 체계, 보고 체계, 회의 계획을 기술합니다.',
    ].join('\n'),
  },
  {
    key: 'quality_and_risk',
    title: '6. 품질보증 및 위험관리 방안',
    prompt: [
      '### 6.1 품질관리 체계',
      '품질관리 조직, 품질관리 기준, 품질 검증 절차를 기술합니다.',
      '### 6.2 품질관리 활동',
      '단계별 품질관리 활동(코드 리뷰, 테스트, 검수 등)을 구체적으로 설명합니다.',
      '### 6.3 위험요소 분석',
      '예상되는 위험요소를 기술적/관리적/외부적 요인으로 분류하여 식별합니다. 위험도(높음/중간/낮음)와 발생 가능성을 평가합니다.',
      '### 6.4 위험 대응 방안',
      '각 위험요소별 예방 조치와 대응 방안을 구체적으로 기술합니다.',
    ].join('\n'),
  },
  {
    key: 'pricing_and_terms',
    title: '7. 사업비 산출 및 계약 조건',
    prompt: [
      '### 7.1 사업비 산출 기준',
      '사업비 산출 근거와 기준을 설명합니다. SW사업 대가산정 기준, 인건비 단가 기준 등을 참조합니다.',
      '### 7.2 사업비 내역',
      '인건비, 경비, 이윤 등 항목별 비용을 표로 정리합니다. 금액이 미정인 항목은 [확인필요]로 표기합니다.',
      '### 7.3 대금 지급 조건',
      '착수금, 중도금, 잔금 등 대금 지급 조건을 기술합니다.',
      '### 7.4 계약 조건',
      '계약 유형, 하자보수 기간, 지적재산권, 비밀유지 등 주요 계약 조건을 정리합니다.',
    ].join('\n'),
  },
  {
    key: 'special_and_approval',
    title: '8. 기타 제안사항 및 승인',
    prompt: [
      '### 8.1 추가 제안사항',
      '특기사항이나 차별화된 제안 내용을 기술합니다. 유사 사업 수행 실적, 기술 역량, 부가 서비스 등을 포함합니다.',
      '### 8.2 보안 및 개인정보 보호',
      '보안 관리 방안과 개인정보 보호 대책을 기술합니다.',
      '### 8.3 교육 및 기술 이전',
      '사업 완료 후 교육 계획과 기술 이전 방안을 기술합니다.',
      '### 8.4 유지보수 및 사후 지원',
      '하자보수 기간, 유지보수 범위, 기술 지원 체계를 기술합니다.',
    ].join('\n'),
  },
];

const PROPOSAL_OUTLINE = [
  '# 제안서',
  '## 1. 제안 개요',
  '## 2. 사업 이해 및 추진 방향',
  '## 3. 수행 범위 및 세부 내용',
  '## 4. 수행 방법 및 일정 계획',
  '## 5. 수행 조직 및 인력 투입 계획',
  '## 6. 품질보증 및 위험관리 방안',
  '## 7. 사업비 산출 및 계약 조건',
  '## 8. 기타 제안사항 및 승인',
].join('\n');

function renderPageFooter() {
  return [
    '<div class="page-footer">',
    '  <div class="footer-left">{{proposer_name}} © {{report_date}}</div>',
    '  <div class="footer-center"></div>',
    '  <div class="footer-right">{{report_title}}</div>',
    '</div>',
  ].join('\n');
}

function renderContentPage(section: TemplateSectionDefinition) {
  return [
    '<section class="sheet page">',
    '  <div class="page-header">',
    `    <h2>{{${section.key}_title}}</h2>`,
    '    <span>Proposal Section</span>',
    '  </div>',
    `  <div class="section-body proposal-body">{{${section.key}_body}}</div>`,
    `  ${renderPageFooter()}`,
    '</section>',
  ].join('\n');
}

function buildProposalHtml(sections: TemplateSectionDefinition[]) {
  const tocRows = sections
    .map((section, index) => [
      '<tr>',
      `  <td>${index + 1}</td>`,
      `  <td>{{${section.key}_title}}</td>`,
      '  <td>자동 생성</td>',
      '</tr>',
    ].join('\n'))
    .join('\n');

  const contentPages = sections.map((section) => renderContentPage(section)).join('\n');

  return [
    '<style>',
    '  @font-face {',
    '    font-family: "Paperlogy";',
    '    src: url("https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2212-02@1.0/Paperlogy-4Regular.woff2") format("woff2");',
    '    font-weight: 400;',
    '    font-style: normal;',
    '  }',
    '  @font-face {',
    '    font-family: "Paperlogy";',
    '    src: url("https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2212-02@1.0/Paperlogy-6SemiBold.woff2") format("woff2");',
    '    font-weight: 600;',
    '    font-style: normal;',
    '  }',
    '  @font-face {',
    '    font-family: "Paperlogy";',
    '    src: url("https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2212-02@1.0/Paperlogy-7Bold.woff2") format("woff2");',
    '    font-weight: 700;',
    '    font-style: normal;',
    '  }',
    '  :root {',
    '    --base: #ffffff;',
    '    --ink: #111111;',
    '    --page-side: 16mm;',
    '    --page-top: 15mm;',
    '    --page-bottom: 16mm;',
    '    --block-gap: 10px;',
    '    --text-gap: 6px;',
    '  }',
    '  * { box-sizing: border-box; }',
    '  body { margin: 0; font-family: "Paperlogy", "Noto Sans KR", sans-serif; color: var(--ink); background: var(--base); line-height: 1.5; counter-reset: page; }',
    '  .proposal-document { width: min(210mm, calc(100% - 24px)); margin: 24px auto 56px; }',
    '  .sheet { width: 210mm; min-height: 297mm; background: var(--base); border: 1px solid var(--ink); margin-bottom: 20px; overflow: hidden; position: relative; counter-increment: page; }',
    '  .cover-main { min-height: 297mm; padding: 18mm 18mm 16mm; position: relative; display: flex; flex-direction: column; }',
    '  .eyebrow { display: inline-block; padding: 0 0 10px; border: none; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }',
    '  .cover-main h1 { margin: 28mm 0 12px; font-size: 44px; line-height: 1.18; letter-spacing: -0.03em; }',
    '  .cover-subtitle { max-width: 660px; font-size: 15px; opacity: 0.78; }',
    '  .cover-side { margin-top: 14mm; display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }',
    '  .meta-block h2, .intro-card h2 { margin: 0 0 16px; font-size: 13px; letter-spacing: 0.08em; text-transform: uppercase; color: var(--ink); }',
    '  .meta-grid { display: grid; gap: 0; }',
    '  .meta-item { display: grid; grid-template-columns: 120px 1fr; gap: 12px; padding: 10px 0; border-bottom: 1px solid var(--ink); }',
    '  .meta-label { display: block; font-size: 12px; opacity: 0.7; }',
    '  .meta-value { font-size: 14px; font-weight: 600; }',
    '  .intro-card { padding: 16px; background: var(--base); border: 1px solid var(--ink); }',
    '  .intro-card p { margin: 0; font-size: 12px; opacity: 0.75; }',
    '  .cover-approval { margin-top: auto; padding-top: 12mm; border-top: 2px solid var(--ink); display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }',
    '  .approval-item { min-height: 74px; padding: 12px 14px; border: 1px solid var(--ink); }',
    '  .approval-item strong { display: block; margin-bottom: 18px; font-size: 12px; }',
    '  .approval-line { border-bottom: 1px solid var(--ink); height: 28px; }',
    '  .page { min-height: 297mm; padding: var(--page-top) var(--page-side) var(--page-bottom); position: relative; }',
    '  .page-header { display: flex; justify-content: space-between; align-items: end; gap: 20px; margin-bottom: 18px; padding-bottom: 10px; border-bottom: 2px solid var(--ink); }',
    '  .page-header h2 { margin: 0; font-size: 22px; letter-spacing: -0.03em; }',
    '  .page-header span { font-size: 11px; opacity: 0.7; }',
    '  table { width: 100%; border-collapse: collapse; margin-top: var(--block-gap); font-size: 12px; table-layout: fixed; }',
    '  th, td { border: 1px solid var(--ink); padding: 8px 10px; vertical-align: top; }',
    '  th { background: var(--base); text-align: left; font-weight: 700; white-space: nowrap; }',
    '  .section-body { font-size: 13px; line-height: 1.5; }',
    '  .proposal-body { padding-left: 28px; }',
    '  .proposal-body p { margin: 0; }',
    '  .proposal-body p + p { margin-top: var(--block-gap); }',
    '  .proposal-body h3 { margin: 0 0 var(--text-gap); padding: 0; font-size: 13px; font-weight: 700; line-height: 1.5; }',
    '  .proposal-body h3:not(:first-child) { margin-top: var(--block-gap); }',
    '  .proposal-body ul, .proposal-body ol { margin: 0; padding-left: 18px; }',
    '  .proposal-body li + li { margin-top: 4px; }',
    '  .proposal-body table { margin-top: var(--block-gap); }',
    '  .proposal-summary { margin-top: var(--block-gap); }',
    '  .summary-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }',
    '  .summary-card { border: 1px solid var(--ink); padding: 14px 16px; min-height: 94px; }',
    '  .summary-card strong { display: block; margin-bottom: 8px; font-size: 12px; }',
    '  .summary-card p { margin: 0; font-size: 12px; line-height: 1.6; }',
    '  .page-footer { position: absolute; left: calc(var(--page-side) + 1px); right: calc(var(--page-side) + 1px); bottom: 8mm; display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; font-size: 10px; }',
    '  .footer-left { text-align: left; white-space: nowrap; position: relative; left: -30px; }',
    '  .footer-center { text-align: center; min-width: 24px; }',
    '  .footer-center::before { content: counter(page); }',
    '  .footer-right { text-align: right; white-space: nowrap; position: relative; right: -30px; }',
    '  @media (max-width: 900px) {',
    '    .proposal-document { width: min(100%, calc(100% - 16px)); }',
    '    .sheet { width: 100%; min-height: auto; }',
    '    .cover-main, .page { padding: 32px 24px; }',
    '    .cover-side, .summary-grid { grid-template-columns: 1fr; }',
    '    .meta-item { grid-template-columns: 1fr; gap: 4px; }',
    '    .page-header { align-items: start; flex-direction: column; }',
    '    .page-footer { left: 24px; right: 24px; }',
    '    .footer-left, .footer-right { left: 0; right: 0; }',
    '  }',
    '</style>',
    '<main class="proposal-document">',
    '  <section class="sheet cover">',
    '    <div class="cover-main">',
    '      <span class="eyebrow">BUSINESS MANAGEMENT INTEGRATED CONSULTING &amp; SERVICES</span>',
    '      <h1>{{project_name}} 제안서</h1>',
    '      <p class="cover-subtitle">본 문서는 공공기관 제출을 위한 제안서 표준양식입니다. 과업 이해, 수행 범위, 일정, 투입 인력 및 비용 조건을 명확하게 제시하는 목적의 공식 문서로 사용합니다.</p>',
    '      <div class="cover-side">',
    '        <div class="meta-block">',
    '          <h2>문서 정보</h2>',
    '          <div class="meta-grid">',
    '            <div class="meta-item"><span class="meta-label">수요기관</span><span class="meta-value">{{demand_org}}</span></div>',
    '            <div class="meta-item"><span class="meta-label">사업명</span><span class="meta-value">{{project_name}}</span></div>',
    '            <div class="meta-item"><span class="meta-label">제안사</span><span class="meta-value">{{proposer_name}}</span></div>',
    '            <div class="meta-item"><span class="meta-label">제출일</span><span class="meta-value">{{report_date}}</span></div>',
    '            <div class="meta-item"><span class="meta-label">문서 제목</span><span class="meta-value">{{report_title}}</span></div>',
    '          </div>',
    '        </div>',
    '        <div class="intro-card">',
    '          <h2>작성 메모</h2>',
    '          <p>{{special_notes}}</p>',
    '        </div>',
    '      </div>',
    '      <div class="cover-approval">',
    '        <div class="approval-item"><strong>작성</strong><div class="approval-line"></div></div>',
    '        <div class="approval-item"><strong>검토</strong><div class="approval-line"></div></div>',
    '        <div class="approval-item"><strong>승인</strong><div class="approval-line"></div></div>',
    '      </div>',
    '    </div>',
    '  </section>',
    '  <section class="sheet page">',
    '    <div class="page-header">',
    '      <h2>목차</h2>',
    '      <span>Table of Contents</span>',
    '    </div>',
    '    <table>',
    '      <thead>',
    '        <tr><th style="width: 18%;">구분</th><th style="width: 58%;">내용</th><th style="width: 24%;">비고</th></tr>',
    '      </thead>',
    '      <tbody>',
    `        ${tocRows}`,
    '      </tbody>',
    '    </table>',
    '    <div class="proposal-summary">',
    '      <div class="summary-grid">',
    '        <div class="summary-card"><strong>제안 목적</strong><p>{{proposal_objective}}</p></div>',
    '        <div class="summary-card"><strong>핵심 수행 범위</strong><p>{{scope_summary}}</p></div>',
    '        <div class="summary-card"><strong>특기사항</strong><p>{{special_notes}}</p></div>',
    '        <div class="summary-card"><strong>참조 문서 요약</strong><p>{{source_file_summary}}</p></div>',
    '      </div>',
    '    </div>',
    `    ${renderPageFooter()}`,
    '  </section>',
    `  ${contentPages}`,
    '</main>',
  ].join('\n');
}

export function isProposalTemplateName(templateName: string | null | undefined) {
  return Boolean(templateName && PROPOSAL_TEMPLATE_PATTERN.test(templateName.trim()));
}

export function createProposalTemplateBundle(): TemplateBundle {
  return {
    version: 1,
    mode: 'html-template',
    layoutHtml: buildProposalHtml(PROPOSAL_SECTIONS),
    outline: PROPOSAL_OUTLINE,
    fields: [...PROPOSAL_FIELDS],
    sections: [...PROPOSAL_SECTIONS],
  };
}
